name: Interactive Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install jupyter
      run: sudo apt-get install jupyter-notebook

    - name: Install nbconvert
      run: pip install nbconvert

    - name: Run tests
      run: make test
